New upstream release [1.6]
Currently FTBFS in unstable:

    /usr/bin/ld: teamdctl.o: undefined reference to symbol 'json_delete'
    /usr/lib/x86_64-linux-gnu/libjansson.so.4: error adding symbols: DSO missing from command line